"""Add name hash to users

Revision ID: 34a51e623757
Revises: 46a278193a94
Create Date: 2023-03-08 13:02:26.795129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34a51e623757'
down_revision = '46a278193a94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name_hash', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name_hash')
    # ### end Alembic commands ###
